//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoipvRemoteTests.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoipvRemoteTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;!-- ****************************************************************--&gt;
        ///&lt;!-- *                                                              *--&gt;
        ///&lt;!-- * PuTTY Configuration Manager save file - All right reserved.  *--&gt;
        ///&lt;!-- *                                                              *--&gt;
        ///&lt;!-- ****************************************************************--&gt;
        ///&lt;!-- The following lines can be modified at your own risks.  --&gt;
        ///&lt;configuration version=&quot;0.7.1.136&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_puttyConnectionManager_database {
            get {
                return ResourceManager.GetString("test_puttyConnectionManager_database", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RDCMan schemaVersion=&quot;1&quot;&gt;
        ///    &lt;version&gt;99.99&lt;/version&gt;
        ///    &lt;file&gt;
        ///    &lt;/file&gt;
        ///&lt;/RDCMan&gt;.
        /// </summary>
        internal static string test_rdcman_badVersionNumber {
            get {
                return ResourceManager.GetString("test_rdcman_badVersionNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RDCMan schemaVersion=&quot;1&quot;&gt;
        ///    &lt;file&gt;
        ///    &lt;/file&gt;
        ///&lt;/RDCMan&gt;.
        /// </summary>
        internal static string test_rdcman_noversion {
            get {
                return ResourceManager.GetString("test_rdcman_noversion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RDCMan schemaVersion=&quot;-99&quot;&gt;
        ///    &lt;version&gt;2.2&lt;/version&gt;
        ///    &lt;file&gt;
        ///    &lt;/file&gt;
        ///&lt;/RDCMan&gt;.
        /// </summary>
        internal static string test_rdcman_v2_2_badschemaversion {
            get {
                return ResourceManager.GetString("test_rdcman_v2_2_badschemaversion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RDCMan schemaVersion=&quot;1&quot;&gt;
        ///    &lt;version&gt;2.2&lt;/version&gt;
        ///    &lt;file&gt;
        ///        &lt;properties&gt;
        ///            &lt;name&gt;test_rdcman_v2_2_schema1&lt;/name&gt;
        ///            &lt;expanded&gt;True&lt;/expanded&gt;
        ///            &lt;comment /&gt;
        ///            &lt;logonCredentials inherit=&quot;FromParent&quot; /&gt;
        ///            &lt;connectionSettings inherit=&quot;FromParent&quot; /&gt;
        ///            &lt;gatewaySettings inherit=&quot;FromParent&quot; /&gt;
        ///            &lt;remoteDesktop inherit=&quot;FromParent&quot; /&gt;
        ///            &lt;localResources inherit=&quot;FromParent&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_rdcman_v2_2_schema1 {
            get {
                return ResourceManager.GetString("test_rdcman_v2_2_schema1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RDCMan programVersion=&quot;2.7&quot; schemaVersion=&quot;3&quot;&gt;
        ///  &lt;file&gt;
        ///    &lt;credentialsProfiles /&gt;
        ///    &lt;properties&gt;
        ///      &lt;expanded&gt;True&lt;/expanded&gt;
        ///      &lt;name&gt;test_RDCMan_connections&lt;/name&gt;
        ///    &lt;/properties&gt;
        ///    &lt;smartGroup&gt;
        ///      &lt;properties&gt;
        ///        &lt;expanded&gt;False&lt;/expanded&gt;
        ///        &lt;name&gt;AllServers&lt;/name&gt;
        ///      &lt;/properties&gt;
        ///      &lt;ruleGroup operator=&quot;All&quot;&gt;
        ///        &lt;rule&gt;
        ///          &lt;property&gt;DisplayName&lt;/property&gt;
        ///          &lt;operator&gt;Matches&lt;/operator&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_rdcman_v2_7_schema3 {
            get {
                return ResourceManager.GetString("test_rdcman_v2_7_schema3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RDCMan programVersion=&quot;2.7&quot; schemaVersion=&quot;3&quot;&gt;
        ///  &lt;file&gt;
        ///    &lt;credentialsProfiles /&gt;
        ///    &lt;properties&gt;
        ///      &lt;expanded&gt;True&lt;/expanded&gt;
        ///      &lt;name&gt;test_RDCMan_connections&lt;/name&gt;
        ///    &lt;/properties&gt;
        ///    &lt;smartGroup&gt;
        ///      &lt;properties&gt;
        ///        &lt;expanded&gt;False&lt;/expanded&gt;
        ///        &lt;name&gt;AllServers&lt;/name&gt;
        ///      &lt;/properties&gt;
        ///      &lt;ruleGroup operator=&quot;All&quot;&gt;
        ///        &lt;rule&gt;
        ///          &lt;property&gt;DisplayName&lt;/property&gt;
        ///          &lt;operator&gt;Matches&lt;/operator&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_rdcman_v2_7_schema3_empty_values {
            get {
                return ResourceManager.GetString("test_rdcman_v2_7_schema3_empty_values", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;RDCMan programVersion=&quot;2.7&quot; schemaVersion=&quot;3&quot;&gt;
        ///  &lt;file&gt;
        ///    &lt;credentialsProfiles /&gt;
        ///    &lt;properties&gt;
        ///      &lt;expanded&gt;True&lt;/expanded&gt;
        ///      &lt;name&gt;test_RDCMan_connections&lt;/name&gt;
        ///    &lt;/properties&gt;
        ///    &lt;smartGroup&gt;
        ///      &lt;properties&gt;
        ///        &lt;expanded&gt;False&lt;/expanded&gt;
        ///        &lt;name&gt;AllServers&lt;/name&gt;
        ///      &lt;/properties&gt;
        ///      &lt;ruleGroup operator=&quot;All&quot;&gt;
        ///        &lt;rule&gt;
        ///          &lt;property&gt;DisplayName&lt;/property&gt;
        ///          &lt;operator&gt;Matches&lt;/operator&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_rdcman_v2_7_schema3_null_values {
            get {
                return ResourceManager.GetString("test_rdcman_v2_7_schema3_null_values", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to screen mode id:i:1
        ///use multimon:i:0
        ///desktopwidth:i:800
        ///desktopheight:i:600
        ///session bpp:i:24
        ///winposstr:s:0,3,0,0,800,600
        ///compression:i:1
        ///keyboardhook:i:2
        ///audiocapturemode:i:0
        ///videoplaybackmode:i:1
        ///connection type:i:7
        ///networkautodetect:i:1
        ///bandwidthautodetect:i:1
        ///displayconnectionbar:i:1
        ///username:s:myusernamehere
        ///enableworkspacereconnect:i:0
        ///disable wallpaper:i:1
        ///allow font smoothing:i:1
        ///allow desktop composition:i:1
        ///disable full window drag:i:1
        ///disable menu anims:i:1
        ///disable themes:i:1
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_remotedesktopconnection_rdp {
            get {
                return ResourceManager.GetString("test_remotedesktopconnection_rdp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;VanDyke version=&quot;3.0&quot;&gt;
        ///	&lt;key name=&quot;Security&quot;&gt;
        ///		&lt;string name=&quot;Passphrase&quot;&gt;03:637dca491ee5dc1979744cecc6d4b0d662285574c56fc6b2aa97afaa2b9a54291e6946f62b0dcb21be8ca375ed236e42694ef1eedebf2aeccf10d40013e6e81d&lt;/string&gt;
        ///	&lt;/key&gt;
        ///	&lt;key name=&quot;Global&quot;&gt;
        ///		&lt;string name=&quot;Active Sessions Manager Window State V2&quot;&gt;2,0,0,-209,117,41,411,0,0,0,0,0&lt;/string&gt;
        ///		&lt;dword name=&quot;Active Window Alpha Transparency&quot;&gt;255&lt;/dword&gt;
        ///		&lt;binary name=&quot;Add Keyword Dialog Size&quot;&gt;2c 00 00 00 00 00 00 00 01 0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string test_securecrt {
            get {
                return ResourceManager.GetString("test_securecrt", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap TestImage {
            get {
                object obj = ResourceManager.GetObject("TestImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

    }
}
