

//Generated for platform: x64

// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;
using System.Resources;

// Compute version values

//Build nr: 0

// General Information
[assembly: AssemblyTitle("LoipvRemote")]
[assembly: AssemblyDescription("LoipvRemote remote connections manager")]
[assembly: AssemblyConfiguration("x64")]
[assembly: AssemblyCompany("Loipv")]
[assembly: AssemblyProduct("LoipvRemote")]
[assembly: AssemblyCopyright("(c) 2026 LoipvRemote")]
[assembly: AssemblyTrademark("LoipvRemote")]
[assembly: AssemblyCulture("")]

// Version information
[assembly: AssemblyVersion("2.0.29.0")]
[assembly: AssemblyFileVersion("2.0.29.0")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("2.0.29 (Internal Build 0) x64")]
