

//Generated for platform: x64

// This code was generated by a script. Any changes made manually will be lost
// the next time this code is regenerated.

using System.Reflection;
using System.Resources;

// Compute version values

//Build nr: 3605

// General Information
[assembly: AssemblyTitle("LoipvRemote")]
[assembly: AssemblyDescription("LoipvRemote remote connections manager")]
[assembly: AssemblyConfiguration("x64")]
[assembly: AssemblyCompany("Loipv")]
[assembly: AssemblyProduct("LoipvRemote")]
[assembly: AssemblyCopyright("(c) 2026 LoipvRemote")]
[assembly: AssemblyTrademark("LoipvRemote")]
[assembly: AssemblyCulture("")]

// Version information
[assembly: AssemblyVersion("1.78.2.3605")]
[assembly: AssemblyFileVersion("1.78.2.3605")]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersion("1.78.2 (Nightly Build 3605) x64")]
